"""empty message

Revision ID: 12a015b65192
Revises: 30c31a6244af
Create Date: 2021-07-10 15:48:54.487041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a015b65192'
down_revision = '30c31a6244af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('alt_number', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('firm', sa.String(length=80), nullable=True),
    sa.Column('ownership', sa.String(length=80), nullable=False),
    sa.Column('vertical', sa.String(length=80), nullable=False),
    sa.Column('services', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('pname', name='person_pname_key')
    )
    op.drop_table('short')
    op.drop_table('detail')
    # ### end Alembic commands ###
