"""empty message

Revision ID: e00a8a88396d
Revises: 0e92274a9a18
Create Date: 2021-07-10 16:43:30.057312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00a8a88396d'
down_revision = '0e92274a9a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('alt_number', sa.String(length=15), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('firm', sa.String(length=80), nullable=True),
    sa.Column('ownership', sa.String(length=100), nullable=False),
    sa.Column('vertical', sa.String(length=500), nullable=False),
    sa.Column('services', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    # ### end Alembic commands ###
